include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    cascade_invocations: false
    sort_child_properties_last: false
    sort_constructors_first: false
    use_key_in_widget_constructors: false
    public_member_api_docs: false
